Pull request to add contact form in Hamayoun Portfolio
Hamayounali/hamayoun-portfolio pull request #10
Opened 2022-06-07 14:07 UTC by Hamayounali

# To Add contact form in Hamayoun portfolio 
1. Updated style.css file 
2. Updated index.html file

2022-06-07 14:12 UTC, leonardodiasb requested changes
# INVALID ❌ ❌ ❌ 

Hi @, 👋

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌
 - You have submitted a Pull Request that has not passed the linters test. Please check your linters before submitting the PR again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

----
_Invalid Code Review Request does not count into the code reviews limit._

2022-06-07 15:39 UTC, Kandy-Peter requested changes
Hi @Hamayounali  

Good job so far! I know you have worked hard on making this milestone. You still need to work on an issue to go to the next project, but you are almost there!

![almost-there-almost](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
- Good commit history :heavy_check_mark: 

## Required Changes ♻️

- [ ] While your design looks nice, it seems like you forgot to generate your hasd_id from [Formspree](https://formspree.io/) and this blocks users from submitting any message. Kindly, go to [Formspree](https://formspree.io/) and generate your unique `hash_id`. You can watch this short [video](https://youtu.be/H_MUJ--iAcc) for guidance. Your form action should look like this: 
```
   <form
      action="https://formspree.io/f/xwkyerln"
      method="POST"
   >
```

- [ ] It would be better if you align your `submit` button to the center to stick the Figma design as required.
**_Your design_**

![image](https://user-images.githubusercontent.com/80612925/172422327-ae7a08f2-f9ce-43e7-bf57-50dba78656db.png)

**The Figma design**
![image](https://user-images.githubusercontent.com/80612925/172422520-5ae2d34b-c17b-4674-9619-18517b99d45a.png)

- [x] Kindly check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-07 16:34 UTC, Hamayounali commented
Hi Kandy Peter. Thank you for the nice suggestions, I have updated accordingly.

2022-06-07 16:48 UTC, rustam-tolipov approved these changes
## Hi @Hamayounali 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-06-07 16:48 UTC, rustam-tolipov commented on assets/css/style.css
> +  padding: 1px;
- [x] [OPTIONAL] GOOD JOB 👏🏼💥🎉✌🏼. I have a suggestion for you to improve your design. As you may know there is a space around your website as you can see down below. You can fix it by adding this code to body in css `margin: 0`. Good luck 🍀🙌🏼👍🏼

![image](https://user-images.githubusercontent.com/69011963/172438048-32c8a0a1-827a-44e7-ae1d-8c7f146526bf.png)

2022-06-08 04:01 UTC, Hamayounali commented on assets/css/style.css
> +  padding: 1px;
Thanks. Noted, but linter doesn't allow 0 value in CSS.

2022-06-08 04:02 UTC, merged