Portfolio details popup window"
Hamayounali/hamayoun-portfolio pull request #19
Opened 2022-06-24 09:49 UTC by Hamayounali

1. Updated index.html file 
2. Updated styles.css file 
3. Updated script.js file 
4. Created popup.js file

2022-06-24 14:30 UTC, ShahierNashaat requested changes
Hi @Hamayounali , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 14:30 UTC, ShahierNashaat commented on assets/js/popup.js
> +];
- [ ] Kindly be noticed that the JavaScript code implements an array of objects to store JavaScript objects containing the information for each project. Each object contains at least the following information about the project: name, description, featured image, technologies, link to the live version, and link to the project source code. Ie:
```javascript
const projects = [{
    name: "Submarine game",
    description: "A Phaser3 platform game built as part of the Microverse JavaScript program.",
    image: "link_to_image.jpg",
    technologies: ["Phaser3", "JavaScript", "Jest"],
    link: "link_to_live_version.com",
}]
```

2022-06-24 14:30 UTC, ShahierNashaat commented on index.html
> +    </div>
- [ ] Please follow the Figma design in your project popup window as you can see in the Figma design there is extra space at the bottom of the mobile popup window.

Your Design | Figma Design
---------------- | --------------------
![Screenshot from 2022-06-24 16-11-44](https://user-images.githubusercontent.com/33752735/175555342-8053c409-ef63-4f56-a608-5c4df9d8b943.png) | ![Screenshot from 2022-06-24 16-11-23](https://user-images.githubusercontent.com/33752735/175555372-b8c862fd-239f-442d-a07f-47f187169053.png)

2022-06-24 14:30 UTC, ShahierNashaat commented on assets/js/popup.js
> +}
- [ ] Kindly be noticed that when the `See Project` button is clicked you should display the right project according to the button ie: if the `See Project` is clicked for `Tonic` project it should display the data for `Tonic` project.

2022-06-24 14:30 UTC, ShahierNashaat commented on index.html
>  	</div>
- [ ] Kindly be noticed that the `See Project` button for some projects is not visible please fix that.

![Screenshot from 2022-06-24 16-27-47](https://user-images.githubusercontent.com/33752735/175556956-199cdbc7-a1ab-45a3-97bd-3f14b8f47262.png)

2022-06-25 10:39 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Hamayounali 

Your project is complete! Great job for making the requested changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Validations correctly implemented
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-25 10:43 UTC, merged