Microvers Pull Request for index.html updates
Hamayounali/hamayoun-portfolio pull request #4
Opened 2022-05-28 11:07 UTC by Hamayounali

Updated Hamayoun project. 
Added Body section and about section in Index.html

Note: Accidentally the updates are curried out on the main branch.

2022-05-28 13:18 UTC, ShahierNashaat requested changes
Hi @Hamayounali and @hamayounali5 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [ ] [Optional] Kindly remove the top part of your design as it just shows how it looks on mobile and not to design it.
![Screenshot from 2022-05-28 14-50-29](https://user-images.githubusercontent.com/33752735/170827295-5011ee68-7836-4c6f-ad5d-a811f636121b.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +		</div>
- [x] Kindly be noticed that the title (e.g., "My Recent Works") uses a header tag `hx`.

2022-05-28 13:18 UTC, ShahierNashaat commented on assets/css/style.css
> +}
- [x] Kindly be noticed that the content of the project is aligned with the flexbox.

2022-05-28 13:18 UTC, ShahierNashaat commented on assets/css/style.css
> +}
- [x] Kindly be noticed that the main container of the projects has a `display:grid`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			<div class="work-sample-2"> Multy-Post Stories </div>
- [x] Kindly be noticed that the project title (e.g., "Tonic") uses a header tag `hx`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			<p class="work-sample"> Profesional Art Printing Data </p>
- [x] Kindly be noticed that the project title (e.g., "Tonic") uses a header tag `hx`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			<p class="work-sample"> Profesional Art Printing Data </p>
- [x] Kindly be noticed that the project title (e.g., "Tonic") uses a header tag `hx`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			<p class="work-sample"> Profesional Art Printing Data </p>
- [x] Kindly be noticed that the project title (e.g., "Tonic") uses a header tag `hx`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			<p class="work-sample"> Profesional Art Printing Data </p>
- [x] Kindly be noticed that the project title (e.g., "Tonic") uses a header tag `hx`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			<p class="work-sample"> Profesional Art Printing Data </p>
- [x] Kindly be noticed that the project title (e.g., "Tonic") uses a header tag `hx`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			<p class="work-sample"> Profesional Art Printing Data </p>
- [x] Kindly be noticed that the project title (e.g., "Tonic") uses a header tag `hx`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			<div class="see-2">See Project</div>
- [x] Kindly be noticed that the button (e.g., "See project") is a link `a` or `button` tag, and follow the button styling: Active, Hover, and Pressed (see design).

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			<div class="see">See Project</div>
- [ ] Kindly be noticed that the button (e.g., "See project") is a link `a` or `button` tag, and follow the button styling: Active, Hover, and Pressed (see design).

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			<div class="see">See Project</div>
- [x] Kindly be noticed that the button (e.g., "See project") is a link `a` or `button` tag, and follow the button styling: Active, Hover, and Pressed (see design).

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			<div class="see">See Project</div>
- [x] Kindly be noticed that the button (e.g., "See project") is a link `a` or `button` tag, and follow the button styling: Active, Hover, and Pressed (see design).

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			<div class="see">See Project</div>
- [x] Kindly be noticed that the button (e.g., "See project") is a link `a` or `button` tag, and follow the button styling: Active, Hover, and Pressed (see design).

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			<div class="see">See Project</div>
- [x] Kindly be noticed that the button (e.g., "See project") is a link `a` or `button` tag, and follow the button styling: Active, Hover, and Pressed (see design).

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			<div class="see">See Project</div>
- [x] Kindly be noticed that the button (e.g., "See project") is a link `a` or `button` tag, and follow the button styling: Active, Hover, and Pressed (see design).

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			</div>
- [ ] Kindly be noticed that the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			</div>
- [ ] Kindly be noticed that the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			</div>
- [ ] Kindly be noticed that the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			</div>
- [ ] Kindly be noticed that the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			</div>
- [ ] Kindly be noticed that the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			</div>
- [ ] Kindly be noticed that the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +			</div>
- [ ] Kindly be noticed that the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +	    </div>
- [ ] Kindly be noticed that the title (e.g., "About myself") uses a header tag `hx`.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +	  	</div>
- [ ] Kindly be noticed that the paragraph (e.g., "I'm a software ...") is a `p` tag.

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +	  	</div>
- [ ] Kindly be noticed that the button (e.g., "Get my resume") is a link `a` or `button` tag, and follow the button styling: Active, Hover, and Pressed (see design).

2022-05-28 13:18 UTC, ShahierNashaat commented on index.html
> +	    </div>
- [ ] Kindly be noticed that the technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li`.
- [ ] And the technology in each category(e.g., "JavasScript", "HTML" and "CSS") are also a list `ul` and each of them a `li`.

2022-05-31 11:14 UTC, Hamayounali commented on assets/css/style.css
> +}
Thank you, I have changed it.

2022-05-31 11:19 UTC, Hamayounali commented on assets/css/style.css
> +}
The content of the project is inside of grid

2022-05-31 15:09 UTC, m05e5 approved these changes
# Hi @Hamayounali , 

### Status: Approved ✔️
![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)


:+1: You have done all the required changes asked by the previous reviewer. Well Done.

Your project is complete! 
Congratulations! 🎉 


**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_m05e5_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 15:09 UTC, m05e5 commented on index.html
> +		<div class="stories">
-  _[optional]_ Please I strongly recommend changing this and the others to `h2`, `h3`, or any other `hx`. As part of the best practices, its recommended to have only one `h1` tag in your file

2022-05-31 15:24 UTC, merged